### ISSUE TITLE
pgjobs-0.2.0

### ISSUE THREAD

**Issue by ktaipakhov** [vinissimus/jobs#2]
Hi! I’ve installed pgjobs-0.2.0 on CentOS 7 with python3.7 (pip3.7 install pgjobs) and I don’t see jobs-migrate in /usr/local/bin, there are only two files jobs-migrator and jobs-worker.
I’ve tried to execute jobs-migrator postgresql://postgres:pass@localhost:5432/postgres and I’m getting this:
Traceback (most recent call last):
  File "./jobs-migrator", line 11, in <module>
    load_entry_point('pgjobs==0.2.0', 'console_scripts', 'jobs-migrator')()
  File "/usr/local/lib/python3.7/site-packages/jobs/migrations.py", line 75, in run
    asyncio.run(main())
TypeError: main() missing 1 required positional argument: 'dsn'
Could you please help me to solve this issue?
 Than you in advance!

**Comment by jordic** [comment]
So many thanks! It should be fixed on 0.2.1
